name: Auto Build Passwall2 OPKG Repo

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip wget jq opkg-utils gzip

      - name: Get latest passwall2 release
        id: release
        run: |
          API="https://api.github.com/repos/Openwrt-Passwall/openwrt-passwall2/releases/latest"
          curl -s $API > release.json

          TAG=$(jq -r .tag_name release.json)

          URL=$(jq -r '.assets[] |
            select(.name | test("24.10.*aarch64")) |
            .browser_download_url' release.json)

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Check if already built
        run: |
          if [ -f .last_version ] && grep -q "${{ steps.release.outputs.tag }}" .last_version; then
            echo "Already up to date"
            exit 0
          fi

      - name: Build repo
        run: |
          rm -rf repo tmp
          mkdir -p repo/passwall2 tmp

          wget -O tmp/passwall2.zip "${{ steps.release.outputs.url }}"
          unzip tmp/passwall2.zip -d tmp

          find tmp -name "*.ipk" -exec mv {} repo/passwall2/ \;

          cd repo/passwall2
          opkg-make-index . > Packages
          gzip -9c Packages > Packages.gz

          cd ../..
          echo "${{ steps.release.outputs.tag }}" > .last_version

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto update passwall2 ${{ steps.release.outputs.tag }}" || exit 0
          git push
